#ifndef _GLOBALS_H
#define _GLOBALS_H

#define IGNORE (void)

enum class Errors_e
{
	NO_ERROR,

	AUDIO_MANAGER_NOT_INITIALIZED,
	AUDIO_MANAGER_NO_USB_CARDS_FOUND,
	AUDIO_MANAGER_CARD_CONFIG_FAILURE,

	AUDIO_RECORDER_NOT_INITIALIZED,
	AUDIO_RECORDER_CAPTURE_EBADFD,
	AUDIO_RECORDER_CAPTURE_EPIPE,
	AUDIO_RECORDER_CAPTURE_ESTRPIPE,
	AUDIO_RECORDER_CAPTURE_EAGAIN,
	AUDIO_RECORDER_CAPTURE_ERROR,
	AUDIO_RECORDER_CALLBACK_ERROR,
	AUDIO_RECORDER_NOT_ENOUGH_SAMPLES,

	AUDIO_CONTROLLER_BUFFER_ERROR,

	APP_CONTAINER_BUFFER_TYPE_ERROR
};

#endif
